- name: play-1
  hosts: localhost
  tasks:
    - name: play-1 & task-1
      ansible.builtin.debug:
        msg: "Hello from Play-1 & Task-1"

    - name: play-1 & task-2
      ansible.builtin.debug:
        msg: "Hello from Play1 & Task-2"
    

- name: play-2
  hosts: localhost
  tasks:
    - name: play-2 & task-1
      ansible.builtin.debug:
        msg: "Hello from play2"