- name: vars from prompt
  hosts: localhost
  vars_prompt:
    - name: username
      prompt: enter username
      private: false # user can see this

    - name: password
      prompt: enter password
      private: true # user cant see this
  tasks:
    - name: printing the values
      ansible.builtin.debug:
        msg: "username is : {{username}} , Password is {{password}}"